import settings

randomaas = "MADKFWLVKEDKALVEHVLGSEAVEFFIWLATNNVLSEFTAPGGDLRVQKGLSQIVEGSNWTYAIYWHVSTSKSGKSALIWGDGHCREPKGSEKKDSEEYNDDNKDRVIVRGDQRKQVLRKIHSCFGGAEDDNVAAKLDSVSEIELFYLTSMYFAFPFDKPSIPSQAFNTSRSIWTSDSKSSLENYQFRSFLAKSAHLESVVFIPLKSGVVEIGSVNSIPEDKNLIQMVKTTFAANVLQSKMSPKIFGQELSLGGGGGGAKSSGPISISFSAKVEDDSGFTSDPYELQAVGSQVYGPSNGFRSSDVDDGPQRNQSGGVSDLEPARDDSLIQSDDRKPRKRGRKPANGREEPLNHVEAERQRREKLNQRFYALRAVVPNISKMDKASLLGDAIAYITDLQKNIRVMETEKEMGSNNNKVKNIIATQNIEFHERHEETIVQVSCPLDTHPVSQVVKALREHQVMAQESNVSLTENGDVLHTFSIQTPGGAAEDLKEKLAAALCK"
mw = 0
for a in randomaas:
    if a in settings.AMINOACIDS:
        mw += settings.AMINOACIDS[a][2]
    else:
        print("Unknown amino acid:", a)
        break
mw += 18.02
print(round(mw, 2))   
